---
apiVersion: v2
name: microservice
version: 0.3.8
appVersion: 0.3.8
description: A Helm chart which provide a DRY microservice deployment mechanism
keywords:
  - microservice
  - template
  - DRY
  - generic
source:
  - https://github.com/jzlotek/helm-microservice
maintainers:
  - name: jzlotek
