# Default values for microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  replicaCount: 1
  environment: []

image:
  repository: "crccheck/hello-world"
  tag: "latest"
  pullPolicy: IfNotPresent

# override the default entrypoint and arguments
# command: cmd
# args:
#  - "arg1"

nameOverride: ""
fullnameOverride: ""

#imagePullSecrets:
#serviceAccount:
# Annotation for the Deployment
annotations: {}

services:
  - name: web
    type: ClusterIP
    annotations: {}
    specs:
    - port: 8000
      targetPort: 8000
      name: http
#targetPort: is the port the container accepts traffic on,
#port: is the abstracted Service port, which can be any port other pods use to access the Service
#https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#serviceport-v1-core

#environment:
#  - name: VAR1
#    value: value1
#  - name: VAR2
#    value: value2
#  - name: VAR1
#    valueFrom:
#      secretKeyRef:
#        name: test-secret
#        key: keyname

### default rollout strategy

# strategy:
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1

livenessEndpoint: /healthz
readinessEndpoint: /healthz

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      servicePort: 8000
      serviceName: web
      path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi
