---
# Source: microservice/templates/service.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-microservice-svc-web
  labels:
    app.kubernetes.io/name: RELEASE-NAME-microservice-svc-web
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Tiller
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: RELEASE-NAME
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-microservice-svc-monitor
  labels:
    app.kubernetes.io/name: RELEASE-NAME-microservice-svc-monitor
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Tiller
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: RELEASE-NAME
  ports:
    - name: monitor
      port: 8001
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-microservice-svc-internal-com
  labels:
    app.kubernetes.io/name: RELEASE-NAME-microservice-svc-internal-com
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: RELEASE-NAME
  ports:
    - name: port1
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: port2
      port: 8002
      protocol: TCP
      nodePort: 30081
---
# Source: microservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-microservice
  labels:
    app.kubernetes.io/name: microservice
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      containers:
        - name: microservice
          image: "strm/helloworld-http:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: monitor
              containerPort: 8001
              protocol: UDP
            - name: port1
              containerPort: 8001
              protocol: TCP
            - name: port2
              containerPort: 8002
              protocol: TCP
          env:
          - name: VAR1
            value: value1
          - name: VAR2
            value: value2
          resources:
            limits:
              cpu: 2
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 500Mi
            
---
# Source: microservice/templates/ingress.yaml

