name: release-chart
on:
  push:
    tags: '*.*.*'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          target_dir: microservice
          charts_dir: .
          charts_url: https://jzlotek.github.io/helm-charts
          owner: jzlotek
          repository: helm-charts
          branch: pages
